### ISSUE TITLE
adjust API to Datomic's client API

### ISSUE THREAD

**Issue by kordano** [replikativ/datahike#196]
refer to [API docs](https://docs.datomic.com/client-api/datomic.client.api.html)
- [x] adapt datahike api namespace
  - [x] delete transact! from api ns
  - [x] adapt datoms
  - [x] adapt seek-datoms
  - [x] adapt pull
  - [x] adapt transact
  - [x] adapt q
- [x] test api in Datahike
- [x] check if return values are comparable (#174)
- [x] adjust also to lazy seqs (#78, #151)
  - [x] implement qseq (#215)
- [x] implement missing Datomic functions
  - [x] implement with-db (not to be implemented now)
  - [x] implement index-pull (not to be implemented now)
  - [x] implement index-range
  - [x] implement tx-range (not to be implemented now)
  - [x] implement timeout ('See namespace doc for timeout and error handling.') (for remote API)
- [x] create async version as well (#188) (After CLJS support is implemented)
- [x] move listen function into api namespace
- [x] prepare empty protocols for functions regarding remote communication
- [x] Add API documentation to docs
- [x] Update [Datomic Differences](https://github.com/replikativ/datahike/blob/development/doc/datomic_differences.md)

**Comment by TimoKramer** [comment]
Regarding empty protocols we decided on implementing a client library following the api namespace to speak to the Datahike server.
